spring.application.name=telcopulse


management.endpoints.web.exposure.include=health,info,metrics,loggers,beans,mappings
management.info.env.enabled=true
info.app.name=telcopulse
info.app.version=1.0.0
info.app.description=Subscriber management API
